<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** Another term for "nodes", they recieve inputs and pass it on to the next set of nodes once a certain thershold is reached.
- **Input Layer:** Also known as the visible layer, it is what the data interacts with directly. hence the name "Inupt"
- **Hidden Layer:** No direct interaction, therefore there's no way to bring them out without the Input layer. They are hidden within the network
- **Output Layer:** Known as the last nodes of the network, Their purpose is to act out as a format that adresses the problem the netowrk is tryin to solve by setting an output vector.
- **Activation:** A transformed output fitted int to a format that will fit the function.
- **Backpropagation:** The use of weights from a neural network and gradient decent to calculate the error function.


## 2. Perceptron on XOR Gates <a id="Q2"></a>

The XOr, or “exclusive or”, problem is a classic problem in ANN research. It is the problem of using a neural network to predict the outputs of XOr logic gates given two binary inputs. An XOr function should return a true value if the two inputs are not equal and a false value if they are equal. Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2 | y |
|---|---|---|
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 1 | 0 |
| 1 | 0 | 1 |


In [150]:
#imports
import pandas as pd
import numpy as np

from tensorflow.keras.utils import to_categorical


In [23]:
#Creating Data
data = { 'x1': [0,0,1,1],
        'x2': [0,1,1,0],
        'y':  [0,1,0,1]
      }

df = pd.DataFrame.from_dict(data)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   1  0
3   1   0  1

In [33]:
#Np Array tranform
X = np.array(df[['x1', 'x2']].values)
Y=np.array(df[['y']].values)
print(X)
print(Y)

[[0 0]
 [0 1]
 [1 1]
 [1 0]]
[[0]
 [1]
 [0]
 [1]]


In [27]:
#Creating Perceptron
class Perceptron(object):
    """Perceptron estimator with early stopping.
    
    :param learning_rate: float Estimator learning rate. Default == 0.01
    :param epochs: int Number of epochs to run Perceptron. Default = 1000
    :param early_stopping: int Number of epochs without imoprovement at which to stop estimator. Default = 10
    
    """
    
    def __init__(self, learning_rate=0.01, epochs=100, early_stopping=10):
        self.lr = learning_rate
        self.epochs = epochs
        self.early_stopping = early_stopping
        
    def predict(self,row):
        """Apply weights and add bias to inputs.
        
        Return 1 if output is greater or equal zero, else zero for each element in input row.
        """
        
        return (np.dot(row, self.weight[1:]) + self.weight[0]) >= 0

    def fit(self, x, y):
        """Fit training data
        
        Initialize with random bias and weights.
        Update weights and bias with each row based on previous iteration's error.
        Store number of errors for each epoch.
        Stop if no errors in number of `early_stopping` epochs.
        """
        
        self.weight = np.array([np.random.random() for _ in range(x.shape[1] + 1)])
    
        self.errors_ = []
        
        for _ in range(self.epochs):
            error = 0
            for row, label in zip(x, y):
                
                # Check our current prediction against the actual label to get the error.
                # Multiply the result by the learning rate.
                adjustment = self.lr * (label - self.predict(row))
                
                # Adjust our weigts and bias accordingly.
                self.weight[1:] += adjustment * row
                self.weight[0] += adjustment
                
                # Add up our errors for each epoch.
                error += adjustment != 0.0
                
            # Make a list of number of errors per epoch.
            self.errors_.append(error)

            # If correct each time for a number of rounds, it will stop already.
            if sum(self.errors_[-self.early_stopping:]) == 0:
                print('Stopped Early')
                break
                
        return self

In [28]:
#Defining
perceptron = Perceptron()

In [29]:
#Fitting
perceptron.fit(X, Y)

In [30]:
#Predicting
perceptron.predict(X)

array([ True,  True, False,  True])

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [157]:
#Load Data
url = 'https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv'
df1 = pd.read_csv(url).values
df1

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [166]:
#spliting input x and output y variables
x = df1[:,0:13]
y = df1[:,13]
y
#numpy arrays
#y_new = np.zeros(y.shape)
#y_new[np.where(y == 0.0)[0]] = 1
#y = y_new
#y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [221]:
class NeuralNetwork:
    def __init__(self):
        self.inputs = 64
        self.hiddenNodes = 32
        self.outputNodes = 1
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, x):
        self.hidden_sum = np.dot(x, self.weights1)
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.sigmoid(self.output_sum)
        return self.activated_output
    
    def backward(self, x, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        self.weights1 += x.T.dot(self.z2_delta)
    
    def train(self, x, y):
        o = self.feed_forward(x)
        self.backward(x, y, o)

In [222]:
nn = NeuralNetwork()
print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 wieghts: \n", nn.weights2)

Layer 1 weights: 
 [[0.03913132 0.34757345 0.08690453 ... 0.13281103 0.46536008 0.01050626]
 [0.91425982 0.24125672 0.93197617 ... 0.70611477 0.77145759 0.85408045]
 [0.57981084 0.87925799 0.44517593 ... 0.52468816 0.57462314 0.99874055]
 ...
 [0.46508551 0.60322434 0.82282193 ... 0.30443618 0.16556039 0.5390551 ]
 [0.61059336 0.76455655 0.52668948 ... 0.67722378 0.49364761 0.50307098]
 [0.85351715 0.12929479 0.14213341 ... 0.11210744 0.09914696 0.2209307 ]]
Layer 2 wieghts: 
 [[0.91904196]
 [0.91251437]
 [0.08468065]
 [0.31731484]
 [0.9821451 ]
 [0.53666093]
 [0.50283707]
 [0.9775469 ]
 [0.64876207]
 [0.05026465]
 [0.90095428]
 [0.86710402]
 [0.36559286]
 [0.54881564]
 [0.6403375 ]
 [0.72586929]
 [0.6763298 ]
 [0.11914422]
 [0.23903809]
 [0.2138331 ]
 [0.95705823]
 [0.30526774]
 [0.07354595]
 [0.65406108]
 [0.21777952]
 [0.3740138 ]
 [0.64504081]
 [0.9261937 ]
 [0.93400441]
 [0.64048911]
 [0.66318737]
 [0.77223021]]


In [223]:
nn = NeuralNetwork()

attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output+']
[print(i+'\n', getattr(nn,i), '\n'+'---'*3) for i in dir(nn) if i[:2]!= '__']

backward
 <bound method NeuralNetwork.backward of <__main__.NeuralNetwork object at 0x14bf46210>> 
---------
feed_forward
 <bound method NeuralNetwork.feed_forward of <__main__.NeuralNetwork object at 0x14bf46210>> 
---------
hiddenNodes
 32 
---------
inputs
 64 
---------
outputNodes
 1 
---------
sigmoid
 <bound method NeuralNetwork.sigmoid of <__main__.NeuralNetwork object at 0x14bf46210>> 
---------
sigmoidPrime
 <bound method NeuralNetwork.sigmoidPrime of <__main__.NeuralNetwork object at 0x14bf46210>> 
---------
train
 <bound method NeuralNetwork.train of <__main__.NeuralNetwork object at 0x14bf46210>> 
---------
weights1
 [[0.70436293 0.89890989 0.56053191 ... 0.82045266 0.4895408  0.06965122]
 [0.19226044 0.31257819 0.74418144 ... 0.59922983 0.38919547 0.77112528]
 [0.96984058 0.19574207 0.40281323 ... 0.51449472 0.96546536 0.30555961]
 ...
 [0.65986452 0.06609291 0.71074347 ... 0.05653763 0.82942011 0.34260953]
 [0.99486099 0.63325643 0.41733619 ... 0.62598943 0.77310389 0.56

[None, None, None, None, None, None, None, None, None, None]

## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [224]:
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [232]:
url = 'https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv'
df2 = pd.read_csv(url)

seed = 42
np.random.seed(seed)

print(df2.shape)
df2.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [228]:
y = df2['target'].values
x = df2.drop('target', axis = 'columns').values

In [246]:
#Create model
def create_model():
    model = Sequential()
    model.add(Dense(12, input_dim=13, activation='relu'))
    model.add(Dense(13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy']) # Fit the model
    return model

#Keras Model
model = KerasClassifier(build_fn=create_model, verbose=1)

In [247]:
#Parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

#Creating Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x, y)

/Users/danielcalimayor/anaconda3/envs/tf/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/20
202/202 [==============================] - 3s 12ms/step - loss: 10.8913 - acc: 0.3168
Epoch 2/20
202/202 [==============================] - 0s 420us/step - loss: 10.8913 - acc: 0.3168
Epoch 3/20
202/202 [==============================] - 0s 435us/step - loss: 10.8913 - acc: 0.3168
Epoch 4/20
202/202 [==============================] - 0s 470us/step - loss: 10.8913 - acc: 0.3168
Epoch 5/20
202/202 [==============================] - 0s 621us/step - loss: 10.8913 - acc: 0.3168
Epoch 6/20
202/202 [==============================] - 0s 590us/step - loss: 10.8913 - acc: 0.3168
Epoch 7/20
202/202 [==============================] - 0s 432us/step - loss: 10.8913 - acc: 0.3168
Epoch 8/20
202/202 [==============================] - 0s 377us/step - loss: 10.8913 - acc: 0.3168
Epoch 9/20
202/202 [==============================] - 0s 434us/step - loss: 10.8913 - acc: 0.3168
Epoch 10/20
202/202 [==============================] - 0s 508us/step - loss: 10.8913 - acc: 0.3168
Epoch 11/20
202/202 

In [248]:
param_grid = {'batch_size': [60],
              'epochs': [20]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x, y)

Epoch 1/20
202/202 [==============================] - 4s 17ms/step - loss: 5.1067 - acc: 0.6832
Epoch 2/20
202/202 [==============================] - 0s 163us/step - loss: 5.1067 - acc: 0.6832
Epoch 3/20
202/202 [==============================] - 0s 121us/step - loss: 5.1067 - acc: 0.6832
Epoch 4/20
202/202 [==============================] - 0s 116us/step - loss: 5.1067 - acc: 0.6832
Epoch 5/20
202/202 [==============================] - 0s 116us/step - loss: 5.1067 - acc: 0.6832
Epoch 6/20
202/202 [==============================] - 0s 106us/step - loss: 5.1067 - acc: 0.6832
Epoch 7/20
202/202 [==============================] - 0s 105us/step - loss: 5.1067 - acc: 0.6832
Epoch 8/20
202/202 [==============================] - 0s 106us/step - loss: 5.1067 - acc: 0.6832
Epoch 9/20
202/202 [==============================] - 0s 98us/step - loss: 5.1067 - acc: 0.6832
Epoch 10/20
202/202 [==============================] - 0s 94us/step - loss: 5.1067 - acc: 0.6832
Epoch 11/20
202/202 [===========

In [249]:
param_grid = {'batch_size': [60, 80],
              'epochs': [20]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(x, y)

print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Epoch 1/20
202/202 [==============================] - 4s 19ms/step - loss: 5.1067 - acc: 0.6832
Epoch 2/20
202/202 [==============================] - 0s 130us/step - loss: 5.1067 - acc: 0.6832
Epoch 3/20
202/202 [==============================] - 0s 122us/step - loss: 5.1067 - acc: 0.6832
Epoch 4/20
202/202 [==============================] - 0s 142us/step - loss: 5.1067 - acc: 0.6832
Epoch 5/20
202/202 [==============================] - 0s 101us/step - loss: 5.1067 - acc: 0.6832
Epoch 6/20
202/202 [==============================] - 0s 115us/step - loss: 5.1067 - acc: 0.6832
Epoch 7/20
202/202 [==============================] - 0s 118us/step - loss: 5.1067 - acc: 0.6832
Epoch 8/20
202/202 [==============================] - 0s 130us/step - loss: 5.1067 - acc: 0.6832
Epoch 9/20
202/202 [==============================] - 0s 128us/step - loss: 5.1067 - acc: 0.6832
Epoch 10/20
202/202 [==============================] - 0s 97us/step - loss: 5.1067 - acc: 0.6832
Epoch 11/20
202/202 [==========