<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import pandas as pd
import numpy as np
data = { 'x1': [0,0,1,0,1,1,0],
         'x2': [0,1,0,1,0,1,0],
         'x3': [1,1,1,0,0,1,0],
         'y' : [0,1,1,1,1,0,0]
      }

df = pd.DataFrame.from_dict(data)
df

x1  x2  x3  y
0   0   0   1  0
1   0   1   1  1
2   1   0   1  1
3   0   1   0  1
4   1   0   0  1
5   1   1   1  0
6   0   0   0  0

In [2]:
X = np.array(df[['x1', 'x2', 'x3']].values)
y = np.array(df['y'].values)

In [3]:
X = X / np.amax(X, axis = 0)
y_new = np.zeros(y.shape)
y_new[np.where(y == 0.0)[0]] = 1
y = y_new

In [4]:
class NeuralNetwork:
    def __init__(self):
        self.inputs = 3
        self.hiddenNodes = 3
        self.outputNodes = 1
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1-s)
    
    def feed_forward(self, X):
        self.hidden_sum = np.dot(X, self.weights1)
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.sigmoid(self.output_sum)
        return self.activated_output
    
    def backward(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivate of sigmoid to error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        self.weights1 += X.T.dot(self.z2_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [5]:
nn = NeuralNetwork()

In [6]:
print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 wieghts: \n", nn.weights2)

Layer 1 weights: 
 [[0.88456219 0.64281878 0.39578009]
 [0.16734568 0.8964779  0.50342004]
 [0.34999486 0.38005974 0.27451642]]
Layer 2 wieghts: 
 [[0.1680773 ]
 [0.320558  ]
 [0.04525772]]


In [7]:
print(X)
output_all = nn.feed_forward(X)
print("output \n", output_all)

[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
output 
 [[0.57802908]
 [0.59554786]
 [0.59770636]
 [0.58587288]
 [0.5880959 ]
 [0.61040053]
 [0.56634313]]


In [8]:
error_all = y[0] - output_all
error_all

array([[0.42197092],
       [0.40445214],
       [0.40229364],
       [0.41412712],
       [0.4119041 ],
       [0.38959947],
       [0.43365687]])

In [9]:
attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output+']
[print(i+'\n', getattr(nn,i), '\n'+'---'*3) for i in dir(nn) if i[:2]!= '__']

activated_hidden
 [[0.58661633 0.59388751 0.56820134]
 [0.62652569 0.78185983 0.68523521]
 [0.77461517 0.73553292 0.66156955]
 [0.54173906 0.71022517 0.62326272]
 [0.70776673 0.65539037 0.59767336]
 [0.80248565 0.87206665 0.76381614]
 [0.5        0.5        0.5       ]] 
---------
activated_output
 [[0.57802908]
 [0.59554786]
 [0.59770636]
 [0.58587288]
 [0.5880959 ]
 [0.61040053]
 [0.56634313]] 
---------
backward
 <bound method NeuralNetwork.backward of <__main__.NeuralNetwork object at 0x10db41610>> 
---------
feed_forward
 <bound method NeuralNetwork.feed_forward of <__main__.NeuralNetwork object at 0x10db41610>> 
---------
hiddenNodes
 3 
---------
hidden_sum
 [[0.34999486 0.38005974 0.27451642]
 [0.51734054 1.27653764 0.77793647]
 [1.23455706 1.02287852 0.67029651]
 [0.16734568 0.8964779  0.50342004]
 [0.88456219 0.64281878 0.39578009]
 [1.40190274 1.91935642 1.17371656]
 [0.         0.         0.        ]] 
---------
inputs
 3 
---------
outputNodes
 1 
---------
output_sum
 [[0

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [14]:
from tensorflow.keras.datasets import mnist

In [16]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [17]:
train_images.shape

(60000, 28, 28)

In [18]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [21]:
network  = models.Sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation = 'softmax'))

network.compile(optimizer = 'rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?